/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_nzdis_sensorspeed_CAccelerometer */

#ifndef _Included_org_nzdis_sensorspeed_CAccelerometer
#define _Included_org_nzdis_sensorspeed_CAccelerometer
#ifdef __cplusplus
extern "C" {
#endif
#undef org_nzdis_sensorspeed_CAccelerometer_MIN_PRIORITY
#define org_nzdis_sensorspeed_CAccelerometer_MIN_PRIORITY 1L
#undef org_nzdis_sensorspeed_CAccelerometer_NORM_PRIORITY
#define org_nzdis_sensorspeed_CAccelerometer_NORM_PRIORITY 5L
#undef org_nzdis_sensorspeed_CAccelerometer_MAX_PRIORITY
#define org_nzdis_sensorspeed_CAccelerometer_MAX_PRIORITY 10L
/*
 * Class:     org_nzdis_sensorspeed_CAccelerometer
 * Method:    accelerometerStartup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_nzdis_sensorspeed_CAccelerometer_accelerometerStartup
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_nzdis_sensorspeed_CAccelerometer
 * Method:    accelerometerShutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_nzdis_sensorspeed_CAccelerometer_accelerometerShutdown
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
