/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_nzdis_sensorspeed_CGyroscope */

#ifndef _Included_org_nzdis_sensorspeed_CGyroscope
#define _Included_org_nzdis_sensorspeed_CGyroscope
#ifdef __cplusplus
extern "C" {
#endif
#undef org_nzdis_sensorspeed_CGyroscope_MIN_PRIORITY
#define org_nzdis_sensorspeed_CGyroscope_MIN_PRIORITY 1L
#undef org_nzdis_sensorspeed_CGyroscope_NORM_PRIORITY
#define org_nzdis_sensorspeed_CGyroscope_NORM_PRIORITY 5L
#undef org_nzdis_sensorspeed_CGyroscope_MAX_PRIORITY
#define org_nzdis_sensorspeed_CGyroscope_MAX_PRIORITY 10L
/*
 * Class:     org_nzdis_sensorspeed_CGyroscope
 * Method:    gyroscopeStartup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_nzdis_sensorspeed_CGyroscope_gyroscopeStartup
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_nzdis_sensorspeed_CGyroscope
 * Method:    gyroscopeShutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_nzdis_sensorspeed_CGyroscope_gyroscopeShutdown
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
