/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_nzdis_sensorspeed_CMagneticField */

#ifndef _Included_org_nzdis_sensorspeed_CMagneticField
#define _Included_org_nzdis_sensorspeed_CMagneticField
#ifdef __cplusplus
extern "C" {
#endif
#undef org_nzdis_sensorspeed_CMagneticField_MIN_PRIORITY
#define org_nzdis_sensorspeed_CMagneticField_MIN_PRIORITY 1L
#undef org_nzdis_sensorspeed_CMagneticField_NORM_PRIORITY
#define org_nzdis_sensorspeed_CMagneticField_NORM_PRIORITY 5L
#undef org_nzdis_sensorspeed_CMagneticField_MAX_PRIORITY
#define org_nzdis_sensorspeed_CMagneticField_MAX_PRIORITY 10L
/*
 * Class:     org_nzdis_sensorspeed_CMagneticField
 * Method:    magneticFieldStartup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_nzdis_sensorspeed_CMagneticField_magneticFieldStartup
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_nzdis_sensorspeed_CMagneticField
 * Method:    magneticFieldShutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_nzdis_sensorspeed_CMagneticField_magneticFieldShutdown
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
