/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_nzdis_sensorspeed_CThreeSensors */

#ifndef _Included_org_nzdis_sensorspeed_CThreeSensors
#define _Included_org_nzdis_sensorspeed_CThreeSensors
#ifdef __cplusplus
extern "C" {
#endif
#undef org_nzdis_sensorspeed_CThreeSensors_MIN_PRIORITY
#define org_nzdis_sensorspeed_CThreeSensors_MIN_PRIORITY 1L
#undef org_nzdis_sensorspeed_CThreeSensors_NORM_PRIORITY
#define org_nzdis_sensorspeed_CThreeSensors_NORM_PRIORITY 5L
#undef org_nzdis_sensorspeed_CThreeSensors_MAX_PRIORITY
#define org_nzdis_sensorspeed_CThreeSensors_MAX_PRIORITY 10L
/*
 * Class:     org_nzdis_sensorspeed_CThreeSensors
 * Method:    threeSensorsStartup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_nzdis_sensorspeed_CThreeSensors_threeSensorsStartup
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_nzdis_sensorspeed_CThreeSensors
 * Method:    threeSensorsShutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_nzdis_sensorspeed_CThreeSensors_threeSensorsShutdown
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
